application: steamplaytime
version: 1
runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: /favicon\.ico
  static_files: favicon.ico
  upload: favicon\.ico

- url: /updateboth
  script: main.app
  login: admin

- url: /gamesupdate
  script: main.app
  login: admin

- url: /hltb
  script: main.app
  login: admin

- url: /stats-update
  script: main.app
  login: admin
  
- url: /testbed
  script: main.app
  login: admin

- url: /style
  static_dir: style

- url: /scripts
  static_dir: scripts

- url: /images
  static_dir: images

- url: .*
  script: main.app

builtins:
- remote_api: on
- appstats: off

libraries:
- name: webapp2
  version: "2.5.2"
- name: jinja2
  version: latest