"""
Several special cases for games

"""

# Games that are multiplayer only. 
mp_games = {570: 'Dota 2', 440: 'TF2',10: 'Counter-Strike',20: 'Team Fortress Classic',
            240: 'CS:S', 17080: 'Tribes: Ascend', 17095: 'Tribes', 17096: 'Tribes',
            17097: 'Tribes',218230: 'PlanetSide 2',219640: 'Chivalry',
            1250: 'Killing Floor',30: 'Day of Defeat',
            204300: 'Awesomenauts', 730: 'CS:GO', 4000: 'Garry\'s Mod',
            4920: 'Natural Selection 2',35420:'Killing Floor',80:'CS',
            35420: 'Killing Floor Mod: Defence Alliance 2',
            80: 'Counter-Strike: Condition Zero',
            4920: 'Natural Selection 2',
            10190: 'Call of Duty: Modern Warfare 2 - Multiplayer',
            35450: 'Rising Storm/Red Orchestra 2 Multiplayer',
            17340: 'Crysis Wars', 42710: 'Call of Duty: Black Ops - Multiplayer',
            2130: 'Dark Messiah Might and Magic Multi-Player',
            104700: 'Super Monday Night Combat',13230: 'Unreal Tournament 2004',
            24860: 'Battlefield 2',1309: 'SiN Multiplayer',102700: 'Alliance of Valiant Arms',
            17500: 'Zombie Panic: Source', 206210: 'Gotham City Imposters',216150: 'Maple Story',
            226700: 'The War Z',231060: 'Ragnarok',237110: 'Mortal Kombat', 24200: 'DC Universe Online',
            300: 'Day of Defeat: Source',90530: "Battle for Graxia",9880: 'Champions Online'}


# Games that either shouldn't be counted, or are duplicates, etc.
outlawed_games = {73030: 'Magicka: Wizard Survival',42918: 'Magicka: Vietnam',3900: 'Sid Meier\'s Civilization IV',
                73031: 'Magicka: Nippon',3990: 'Sid Meier\'s Civilization IV: Warlords',34460: 'Sid Meier\'s Civilization IV: Beyond the Sword',
                18509: 'Defense Grid: Resurgence Map Pack 2 ',18508: 'Defense Grid: Resurgence Map Pack 1',18520: 'Defense Grid: Resurgence Map Pack 3',
                18521: 'Defense Grid: Resurgence Map Pack 4',207080: 'Indie Game: The Movie',73035: 'Magicka: Final Frontier',
                73037: 'Magicka: Frozen Lake',73036: 'Magicka: The Watchtower',31200: 'Tales of Monkey Island: Chapter 4 - The Trial and Execution of Guybrush Threepwood ',
                31210: 'Tales of Monkey Island: Chapter 5 - Rise of the Pirate God',31190: 'Tales of Monkey Island: Chapter 3 - Lair of the Leviathan ',
                107410: 'Arma 3 Beta',31170: 'Tales of Monkey Island: Chapter 1 - Launch of the Screaming Narwhal',207815: 'PAYDAY: Wolf Pack',
                13140: 'America\'s Army 3',94520: 'Back to the Future: Ep 4 - Double Visions',
                94500: 'Back to the Future: Ep 2 - Get Tannen!',94510: 'Back to the Future: Ep 3 - Citizen Brown',
                94530: 'Back to the Future: Ep 5 - OUTATIME',104600: 'Portal 2: Final Hours',
                227320: 'You Need a Budge',340: 'HL2: Lost Coast',55370: 'Saints Row DLC'
                }

# Sometimes the search name used in HLTB doesn't match the search name we grab from Steam. This requires some work done by hand;
# any that are found are added here, mapping what the search name should be set as for both HLTB and Steam.
hltb_names = {
      'deusex': 'deusexgameoftheyearedition',
      'deusexhumanrevolutionthemissinglinkdlc': 'deusexhumanrevolutionthemissinglink',
      'assassinscreedii': 'assassinscreed2deluxeedition',
      'batmanarkhamasylum': 'batmanarkhamasylumgameoftheyearedition',
      'borderlandsmadmoxxisunderdomeriotdlc': 'borderlandsmadmoxxisunderdomeriot',
      'borderlandsthesecretarmoryofgeneralknoxxdlc': 'borderlandsthesecretarmoryofgeneralknoxx',
      'borderlandsthezombieislandofdrneddlc': 'borderlandsthezombieislandofdrned',
      'sidmeierscivilizationivbeyondthesword': 'civilizationivbeyondthesword',
      'crysis2': 'crysis2maximumedition',
      'maxpayne2thefallofmaxpayne': 'maxpayne2',
      'organtrail': 'organtraildirectorscut',
      'penumbrablackplague': 'penumbrablackplaguegoldedition',
      'thesecretofmonkeyisland': 'thesecretofmonkeyislandspecialedition',
      'thewitcher2assassinsofkings': 'thewitcher2assassinsofkingsenhancededition',
      'thewitcher': 'thewitcherenhancededitiondirectorscut',
      'trine2': 'trine2completestory',
      'warhammer40000dawnofwar': 'warhammer40000dawnofwargameoftheyearedition',
      'crysiswarhead':'crysiswarhead',
      'mirrorsedge':'mirrorsedge',
      'tinyandbiggrandpasleftovers':'tinyandbiggrandpasleftovers',
      'batmanarkhamasylum':'batmanarkhamasylumgameoftheyearedition',
      'assassinscreedii':'assassinscreed2deluxeedition',
      'brokenswordtheshadowofthetemplarsdirectorscut':'brokenswordshadowofthetemplarsdirectorscut',
      'sidmeierscivilizationivbeyondthesword':'civilizationivbeyondthesword',
      'backtothefuturethegame':'backtothefuturethegame',
      'hectorbadgeofcarnageepisode1':'hectorepisode1',
      'hectorbadgeofcarnageepisode2senselessactsofjustice':'hectorepisode2',
      'plantsvszombies': 'plantsvszombiesgameoftheyear',
      'serioussamhdthefirstencounter': 'serioussamclassicthefirstencounter',
      'serioussamhdthesecondencounter': 'serioussamclassicthesecondencounter',
      'falloutnewvegasdeadmoneydlc': 'falloutnewvegasdeadmoney',
      'falloutnewvegashonestheartsdlc': 'falloutnewvegashonesthearts',
      'monkeyisland2lechucksrevenge': 'monkeyisland2specialedition',
      'fallout3gameoftheyear': 'fallout3gameoftheyearedition',
      'batmanarkhamasylum': 'batmanarkhamasylumgotyedition',
      'unrealtournament3': 'unrealtournament3blackedition',
      'pennyarcadeadventuresprecipiceofdarknessepisodethree': 'pennyarcadesontherainslickprecipiceofdarkness3',
      'timegentlemenplease': 'timegentlemen',
      'bentheredanthat': 'benthere',
      'burnoutparadise': 'burnoutparadisetheultimatebox',
      'aaaaaaaaaaaaaaaaaaaaaaaaaarecklessdisregardforgravity': 'aaaaaaarecklessdisregardforgravity',
      'tropico3': 'tropico3steamspecialedition',
      'simcity4': 'simcity4deluxe',
      'freedomforce2002': 'freedomforce',
      'breathofdeathviithebeginning': 'breathofdeathvii',
      'hitmanabsolutionsniperchallenge': 'hitmansniperchallenge',
      'aliensvspredator2010': 'aliensvspredator',
      'darkmessiahofmightandmagic': 'darkmessiahmightandmagicsingleplayer',
      'theship': 'theshipsingleplayer',
      'starwarsknightsoftheoldrepubliciithesithlords': 'starwarsknightsoftheoldrepublicii',
      'painkillergoldblackedition': 'painkillerblackedition',
      'commanderkeen1maroonedonmars': 'commanderkeencompletepack',
      'hexen': 'hexenbeyondheretic',
      'unrealtournament': 'unrealtournamentgameoftheyearedition',
      'serioussamii': 'serioussam2',
      'europauniversalisiii': 'europauniversalisiiiheirtothethrone',
      'scratches': 'scratchesdirectorscut',
      'europauniversalisiii': 'europauniversalisiiidivinewind',
      'patricianiv': 'patricianivsteamspecialedition'
}